import Head from "next/head";
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/Sanskar_Gupta.jpeg";
import Image from "next/image";
import web1 from "../public/web1.jpeg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";
import web4 from "../public/web4.jpg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Sanskar</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/16lrbTvHUbVsU4LZXkIoWI5RF2v8n41Dh/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Sanskar Gupta
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Web-Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Under Graduate Full Stack Web Development and Programming. Capable leader, self-motivated, result-oriented, 
            and working on many end-to-end projects. 
            experienced with Javascript, Python and C++.
            </p>
            
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-[50vw] h-[28vh] relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                🔭 I’m a full stack Web Developer
                <br/>
                🌱 I’m currently learning AI/ML & improving my Problem Solving skills
                <br/>
                👯 I’m looking to collaborate for projects and hackathons
                <br/>
                ⚡ Fun fact: I am still a newbie😄.
                <br/>
                😍 Interested to build tech that solve real world problem
                <br/>
                📫 You can reach me through 👇
                <br/>
                <br/>
                <div className="text-5xl flex justify-start gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/sanskar0901"><AiFillGithub className="hover:text-cyan-500"/></a>
              <a href="https://www.linkedin.com/in/sanskar-gupta-0354b21b7/"><AiFillLinkedin className="hover:text-cyan-500" /></a>
              <a href="https://www.instagram.com/sanskargupta_09/"><AiFillInstagram className="hover:text-cyan-500" /></a>
            </div>
            </p>
            
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done Many Projects.
              and also collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-[2_2_0%] ">
          <a href="https://shoe-customizer.netlify.app/">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"75%"}
                layout="responsive"
                src={web1}
              />
            </a>
            </div>
            <div className="basis-1/3 flex-[2_2_0%]">
            <a href="#">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"75%"}
                layout="responsive"
                src={web2}
              />
              </a>
            </div>
            <div className="basis-1/3 flex-[2_2_0%]">
            <a href="https://0fitify0.netlify.app/">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"75%"}
                layout="responsive"
                src={web3}
              />
            </a>
            </div>
           <div className="basis-1/3 flex-[2_2_0%]">
           <a href="https://0sehyog0.netlify.app/">
              <Image
                className="rounded-lg"
                width={"100%"}
                height={"75%"}
                layout="responsive"
                src={web4}
              />
            </a>
            </div>
            
            
          </div>
        </section>
      </main>
    </div>
  );
}
