import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { FaKaggle } from "react-icons/fa";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import MLcert from "../public/MLcert.png";
import Google from "../public/Google.png";
import polyu from "../public/polyu.png";
import vtc from "../public/vtc.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kenneth Lo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className=" text-black py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              Developed by
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="dark:text-white cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  class="invisible opacity-0"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Kenneth Lo
            </h2>
            <h3 className="text-2xl py-2 text-black md:text-3xl dark:text-white">
              ML Engineer / Software Developer
            </h3>
            <p className="text-gray-800 text-md py-5 leading-8 md:text-xl max-w-xl mx-auto dark:text-white">
              Hi, I'm Kenneth, a data enthusiast, machine learning practitioner
              and software developer. My passion lies in exploring and analyzing
              complex data sets, identifying patterns, and deriving insights to
              help drive informed decision-making.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://twitter.com/Kenneth04718429" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/kenneth-lo-84a871259/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/HkgCory" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.kaggle.com/lokinhang" target="_blank">
              <FaKaggle />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-cyan-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={deved}
              className="absolute inset-0 w-full h-full object-cover object-center"
            />
          </div>
        </section>

        <section>
          <div className="text-center py-2">
            <h3 className="text-3xl py-1 text-gray-800 dark:text-white">
              Skill Set
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              With my strong proficiency in JS, HTML, CSS, Solidity, Python, R
              and SQL, I excel in data analysis, machine learning, deep
              learning, and artificial intelligence. I believe that data-driven
              decision-making is the key to unlocking the full potential of any
              business or organization, and I strive to help organizations
              leverage the power of data to achieve their goals.
              {/* <span className="text-teal-500 dark:text-white">Certificate</span> */}
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
            test test test testt
            <span className="text-teal-500 dark:text-white">Certificate</span>
          </p> */}
          </div>

          <div className="flex justify-center gap-10">
            <div className="flex-1 text-center shadow-lg p-10 rounded-xl my-10 bg-gray-800 dark:bg-yellow-200">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-10 text-amber-200  dark:text-teal-900">
                Experiences:
              </h3>

              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Machine Learning
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Deep Learning
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Data Analysis
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Web 3.0 Development
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                ERC-20/721 Smart Contract
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Frontend Web Development
              </p>
            </div>

            <div className="flex-1 text-center shadow-lg p-10 rounded-xl my-10 bg-gray-800 dark:bg-yellow-200">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-10 text-amber-200  dark:text-teal-900">
                Programming Languages:
              </h3>

              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Python
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">SQL</p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                Solidity
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                JavaScript (React)
              </p>
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                HTML / CSS
              </p>
            </div>

            <div className="flex-1 text-center shadow-lg p-10 rounded-xl my-10 bg-gray-800 dark:bg-yellow-200">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-10 text-amber-200  dark:text-teal-900">
                Languages:
              </h3>
              {/* <p class='invisible opacity-0' className="py-2  text-amber-200  dark:text-teal-900">
  test test test test
</p>
<h4 className="invisible opacity-0 py-4 text-teal-200 dark:text-emerald-800">
  Programming Languages
</h4> */}
              <p className="py-2 text-teal-200  dark:text-emerald-800">
                English
                <span className="block py-1 my-1 text-amber-200  dark:text-teal-900 text-sm">
                  (Full Professional Proficiency)
                </span>
              </p>

              <p className="py-2  text-teal-200  dark:text-emerald-800">
                Cantonese
                <span className="block py-1 my-1 text-amber-200  dark:text-teal-900 text-sm">
                  (Native Proficiency)
                </span>
              </p>
              <p className="py-2  text-teal-200  dark:text-emerald-800">
                Mandarin
                <span className="block py-1 my-1 text-amber-200  dark:text-teal-900 text-sm ">
                  (Full Professional Proficiency)
                </span>
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="text-center shadow-lg p-10 my-10 rounded-xl">
            <h3 className="text-3xl py-1 text-gray-800  dark:text-white">
              Certificate
            </h3>
            {/* <p className="py-2  text-gray-800  dark:text-white">
            test test test test
          </p> */}

            <div className="flex  gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/4 flex-1  ">
                <a href="https://www.udemy.com/certificate/UC-d1bc46b3-e7c0-40c5-b9dc-f54fb9086df5/">
                  <Image
                    src={MLcert}
                    className="rounded-lg object-cover h-full w-full"
                    width={300}
                    height={300}
                    style={{ objectPosition: "50% 50%" }}
                  />
                </a>
                <p className="mt-3 text-center text-gray-600 dark:text-white">
                  Complete Machine Learning & Data Science Certificate by Udemy
                </p>
              </div>

              <div className="basis-1/4 flex-1">
                <a href="https://www.coursera.org/account/accomplishments/specialization/certificate/GZ3NDN7WMRR9">
                  <Image
                    src={Google}
                    className="rounded-lg object-cover"
                    width={300}
                    height={300}
                    style={{ objectPosition: "50% 50%" }}
                  />
                </a>
                <p className="mt-3 text-center text-gray-600 dark:text-white">
                  Google Data Analtics Certificate by Coursera
                </p>
              </div>
            </div>

            <h3 className="text-3xl py-1 text-gray-800  dark:text-white">
              Education
            </h3>
            {/* <p className="py-2  text-gray-800  dark:text-white">
            test test test test
          </p> */}

            <div className="flex  gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/4 flex-1  ">
                <a href={polyu.src}>
                  <Image
                    src={polyu}
                    className="rounded-lg object-cover max-w-full mx-auto"
                    width={300}
                    height={300}
                    style={{ objectPosition: "50% 50%" }}
                  />
                </a>

                <p className="mt-3 text-center text-gray-600 dark:text-white">
                  Bachelor of Engineering in Electronic and Information
                  Engineering by the Hong Kong Polyutechnic university
                  <span className="block  text-gray-600 dark:text-white text-sm ">
                    Graduated in September 2022
                  </span>
                </p>
              </div>

              <div className="basis-1/4 flex-1">
                <a href={vtc.src}>
                  <Image
                    src={vtc}
                    className="rounded-lg object-cover mx-auto"
                    width={200}
                    height={300}
                    style={{ objectPosition: "50% 50%" }}
                  />
                </a>
                <p className="mt-3 text-center text-gray-600 dark:text-white">
                  Associate Diploma in Electrical Engineering by the Hong Kong
                  Institute of Vocational Education
                  <span className="block  text-gray-600 dark:text-white text-sm ">
                    Graduated in June 2019
                  </span>
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
