import Head from "next/head";
import { useState } from "react";
import Navbar from "../components/Navbar";
import Introduction from "../components/Introducton";
import ServicesOffer from "../components/ServicesOffer";
import PortFolio from "../components/PortFolio";
import { NextPageContext } from "next/types";

export default function Home({ isUserKorean }) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>PortFolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-[#E7F6F2] px-10 dark:bg-[#2C3333] transition ease-in-out duration-500 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <Navbar
            darkMode={darkMode}
            setDarkMode={setDarkMode}
            isUserKorean={isUserKorean}
          />
          <Introduction isUserKorean={isUserKorean} />
        </section>
        <ServicesOffer />
        <PortFolio />
      </main>
    </div>
  );
}

export async function getServerSideProps({ req }: NextPageContext) {
  const userlanguages =
    typeof navigator === "undefined"
      ? req.headers["accept-language"].split(",")
      : ["en"];

  const isUserKorean = userlanguages.includes("ko-KR") ? true : false;

  return { props: { isUserKorean } };
}
